### ISSUE TITLE
rbircd won't start

### ISSUE THREAD

**Issue by Steve-John** [danopia/rbircd#2]
```
root@li140-48:~/rbircd-master# ruby ircd.rb
ircd.rb:38:in `load': ircclient.rb:145: syntax error, unexpected tSTRING_BEG, expecting ':' (SyntaxError)
                                (value == true) ? key.upcase"#{key.upcase}=#{value}"
                                                             ^
        from ircd.rb:38:in `reload!'
        from ircd.rb:41:in `<main>'
root@li140-48:~/rbircd-master#
```

**Comment by danopia** [comment]
I fixed that specific problem in 88d2c5241d5ff0afbb92fb503ff659f3d2ca414d. Please try again. Hopefully nothing else is wrong in the code.

Please keep in mind that rbircd is an old project that I haven't supported in years, though it should still work.

**Comment by Steve-John** [comment]
@danopia Hi!

Yes I noticed that it hadn't been updated in years, but I wanted to give it a shot!

Your commit did sort that particular error message but I now get:

```
root@li140-48:~/rbircd-master# ruby ircd.rb 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- lineconnection (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from ircclient.rb:28:in `<top (required)>'
	from ircd.rb:38:in `load'
	from ircd.rb:38:in `reload!'
	from ircd.rb:41:in `<main>'
root@li140-48:~/rbircd-master# 
```

There is no gem called `lineconnection` though, so I can't install it!

Am I missing something?

**Comment by danopia** [comment]
lineconnection is a file in the repo. You should be able to fix that require with something like: `require './lineconnection'`. This is probably a problem from ruby versioning. If other things crop up I'll clone rbIRCd tonight and fix it up completely

**Comment by Steve-John** [comment]
Thanks. Fixed by changing `ircclient.rb:28` to `require './lineconnection.rb'` as suggested!

I'm not sure how much you are interested in this anymore but I have noticed thus far that it is not possible to create a channel with underscores (possibly other characters but I haven't tested) and you can also have 2 users connected with the same nickname!

**Comment by danopia** [comment]
There's a bunch of symbols allowed, but underscores wasn't one of them.
Source: https://github.com/danopia/rbircd/blob/master/ircserver.rb#L82

And yea it certainly looks like multiple nicks are allowed! There's no check here:
https://github.com/danopia/rbircd/blob/master/ircclient.rb#L253

Pull requests are welcome to fix up all the random issues like that! I'm going to fix the `require` statement and close this issue.
