### ISSUE TITLE
Users using lightIRC connect but can't JOIN

### ISSUE THREAD

**Issue by ircer** [danopia/rbircd#4]
Users using lightIRC connect but can't JOIN.

lightIRC is RFC compliant, so I assume rbircd is missing sending something to clients or something or other.

I'll check if I get chance.

**Comment by danopia** [comment]
The problem is that rbIRCd only sends `\n` to end lines, which is more Linux-style. Windows stuff ends lines in `\r\n`. When I change rbIRCd to send Windows-style newlines, lightIRC connects right away.

Since all clients should be able to handle `\r\n` I will swap out the newlines sent.

**Comment by danopia** [comment]
Note that lightIRC seems to have other issues with compatibility. When rbIRCd sends single-word content, it takes the opportunity to skip on putting a `:` before the content.

As far as I know this is totally valid, but lightIRC pretends it doesn't see any content, just an empty message.

**Comment by ghost** [comment]
Is there something that can be done about your last comment @danopia?

I spoke to the author and he says that his client is RFC compliant and can't/won't do anything to sort it as no other IRC servers have the same issue.
